### ISSUE TITLE
[Bug][v0.2]: memmachine.semantic_memory.semantic_memory - background task keep crashing

### ISSUE THREAD

**Issue by yufangmv** [MemMachine/MemMachine#610]
### Describe the bug

[Bug][v0.2]: memmachine.semantic_memory.semantic_memory - background task keep crashing

### Steps to reproduce

**Step 1: add memory**
```
yufang@Memverges-MacBook-Pro MemMachine % curl -X POST "http://localhost:8080/api/v2/memories" \        
-H "Content-Type: application/json" \
-d '{
    "org_id": "org_sample",
    "project_id": "project_sample",
    "messages": [
        {
            "content": "This is to test memory content from user_sample to agent_sample",
            "producer": "user_sample",
            "produced_for": "",
            "timestamp": "2019-08-24T14:15:22Z",
            "metadata": {
                "department": "AI Research",
                "priority": "high",
                "agent_id": "agent_sample",
                "user_id": "user_sample"
            }
        }
    ]
}'
{"results":[{"uid":"124"}]}%  
```

**Step 2: delete project**
```
yufang@Memverges-MacBook-Pro MemMachine %  curl -X POST "http://localhost:8080/api/v2/projects/delete" \
-H "Content-Type: application/json" \
-d '{
  "org_id": "org_sample",  
  "project_id": "project_sample"   
}'               
yufang@Memverges-MacBook-Pro MemMachine
```

**Step 3: check postgresql database**
```
postgres=# select * from set_ingested_history;
                set_id                 | history_id | ingested 
---------------------------------------+------------+----------
 mem_session_org_sample/project_sample | 124        | f
(1 row)

postgres=# select * from episodestore;
 id | content | session_key | producer_id | producer_role | produced_for_id | episode_type | metadata | created_at 
----+---------+-------------+-------------+---------------+-----------------+--------------+----------+------------
(0 rows)

postgres=# 
```

**Step 4: add more memory**
```
yufang@Memverges-MacBook-Pro MemMachine % curl -X POST "http://localhost:8080/api/v2/memories" \
-H "Content-Type: application/json" \
-d '{
    "org_id": "org_sample",
    "project_id": "project_sample",
    "messages": [
        {
            "content": "This is to test memory content from user_sample to agent_sample",
            "producer": "user_sample"
        },
        {
            "content": "This is to test memory content from user_sample to agent_sample",
            "producer": "user_sample"
        },
        {
            "content": "This is to test memory content from user_sample to agent_sample",
            "producer": "user_sample"
        },
        {
            "content": "This is to test memory content from user_sample to agent_sample",
            "producer": "user_sample"
        }
    ]
}'
{"results":[{"uid":"125"},{"uid":"126"},{"uid":"127"},{"uid":"128"}]}%
```

**Step 5: app.py, keep crashing at memmachine.semantic_memory.semantic_memory**
```
2025-11-25 16:36:09,816 [ERROR] memmachine.semantic_memory.semantic_memory - background task crashed, restarting
  + Exception Group Traceback (most recent call last):
  |   File "/Users/yufang/test/MemMachine/src/memmachine/semantic_memory/semantic_memory.py", line 267, in _background_ingestion_task
  |     await ingestion_service.process_set_ids(dirty_sets)
  |   File "/Users/yufang/test/MemMachine/src/memmachine/semantic_memory/semantic_ingestion.py", line 66, in process_set_ids
  |     raise ExceptionGroup("Failed to process set ids", errors)
  | ExceptionGroup: Failed to process set ids (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/yufang/test/MemMachine/src/memmachine/semantic_memory/semantic_ingestion.py", line 91, in _process_single_set
    |     raise ValueError("Failed to retrieve messages. Invalid history_ids")
    | ValueError: Failed to retrieve messages. Invalid history_ids
    +------------------------------------
```

**Step 6: in postgresql**
```
postgres=# select * from set_ingested_history;
                set_id                 | history_id | ingested 
---------------------------------------+------------+----------
 mem_session_org_sample/project_sample | 125        | f
 mem_session_org_sample/project_sample | 126        | f
 mem_session_org_sample/project_sample | 127        | f
 mem_session_org_sample/project_sample | 128        | f
 mem_session_org_sample/project_sample | 124        | f
(5 rows)

postgres=# select * from episodestore;
 id  |                             content                             |        session_key        | producer_id | producer_role | produced_for_id | episode_type | metadata |          created_at           
-----+-----------------------------------------------------------------+---------------------------+-------------+---------------+-----------------+--------------+----------+-------------------------------
 125 | This is to test memory content from user_sample to agent_sample | org_sample/project_sample | user_sample |               |                 | MESSAGE      | {}       | 2025-11-25 16:24:35.024757-08
 126 | This is to test memory content from user_sample to agent_sample | org_sample/project_sample | user_sample |               |                 | MESSAGE      | {}       | 2025-11-25 16:24:35.024771-08
 127 | This is to test memory content from user_sample to agent_sample | org_sample/project_sample | user_sample |               |                 | MESSAGE      | {}       | 2025-11-25 16:24:35.024775-08
 128 | This is to test memory content from user_sample to agent_sample | org_sample/project_sample | user_sample |               |                 | MESSAGE      | {}       | 2025-11-25 16:24:35.024778-08
(4 rows)

postgres=# 

```

### Expected behavior

Should not crash

### Environment

MacOS: 15.6.1
MemMachine: c79799c [v0.2]

**Comment by o-love** [comment]
Fix merged into dev/v0.2 branch in https://github.com/MemMachine/MemMachine/pull/542/commits/43396319cf8c78b1002bbd45ed76c941ecd0ae17

Root cause was that when deleting from episodic store we don't remove from semantic storage.

Could you validate.

**Comment by ChristianKniep** [comment]
Yes, now the response matches. 👍

**Comment by ChristianKniep** [comment]
closing, thanks!

**Comment by yufangmv** [comment]
@o-love the issue is still there.  tested with dev/v0.2 branch https://github.com/MemMachine/MemMachine/commit/da78d41bb4f57a95a62b0c521b0b254bd4e72f70

**Comment by o-love** [comment]
@yufangmv Fixed delete project endpoint issue in [cc9272b](https://github.com/MemMachine/MemMachine/pull/542/commits/cc9272be57e6fd57c0b7e971e5f6f8e30148dfa4)

**Comment by yufangmv** [comment]
Verified fix with dev/v0.2 branch [cc9272b](https://github.com/MemMachine/MemMachine/pull/542/commits/cc9272be57e6fd57c0b7e971e5f6f8e30148dfa4)

After **Step 2: delete project**, no rows in set_ingested_history table.
